# Generated by Django 4.2.3 on 2023-07-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tarefa_descricao_tarefa_finalizado_tarefa_prazo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='finalizado',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='prazo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
