# Generated by Django 4.2.3 on 2023-07-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_tarefa_descricao_alter_tarefa_finalizado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='prazo',
            field=models.DateField(blank=True, null=True),
        ),
    ]
